services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          target: /app
          ignore:
            - "frontend/node_modules"
            - "frontend/.next"
            - "frontend/.git"
            - "frontend/package-lock.json"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/f1_data.db:/app/f1_data.db
    environment:
      - PYTHONUNBUFFERED=1
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /app
          ignore:
            - "backend/__pycache__"
            - "backend/.git"
            - "backend/f1_data.db"
            - "backend/*.pyc"
            - "backend/.pytest_cache"
            - "backend/*.log" 